language: python
sudo: false
python:
  - "3.5"
  - "3.6"
install:
  - python3 -m pip install --upgrade . coverage coveralls
script:
  - python3 -m coverage run -m unittest -b
after_success:
  - coveralls
# vim: ts=2:sts=2:sw=2:et
